name: Increment Version
descriptionaa: a fork of christian-draeger/increment-semantic-version, Bump a given semantic version by a release type ( major | minor | patch ) and add a possible postfix ( alpha | beta | rc )
author: Nathan Tamez
branding:
  icon: 'tag'
  color: 'purple'
inputs:
  current-version:
    description: 'The current semantic version you want to increment'
    required: true
  version-fragment:
    description: 'The versions fragment you want to increment. possible options are [ major | feature | bug | alpha | beta | rc ]'
    required: true
outputs:
  next-version:
    description: 'The incremented version'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.current-version }}
    - ${{ inputs.version-fragment }}
